apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qdrouterd
  labels:
    app: qdrouterd
spec:
  replicas: 1
  template:
    metadata:
      name: qdrouterd
      labels:
        app: qdrouterd
    spec:
      containers:
        - image: qpid-dispatch:0.6.1  #scholzj/qpid-dispatch:0.6.0
          name: qdrouterd
          #imagePullPolicy: Always
          env:
            - name:  QDROUTERD_ADMIN_USERNAME
              value: admin
            - name:  QDROUTERD_ADMIN_PASSWORD
              value: "123456"
            - name: QDROUTERD_CONFIG_OPTIONS
              value: |
                router {
                  mode: standalone
                  id: ZTZiNmVlZTM2ZjljZDA2N2MwY2I2NWI3
                  workerThreads: 4
                } 
                listener {
                  role: normal
                  host: 0.0.0.0
                  port: 10452
                  linkCapacity: 1000
                }
                log {
                  module: DEFAULT
                  enable: trace+
                  timestamp: true
                }
                connector {
                  name: shard_0
                  role: route-container
                  host: 172.17.0.5
                  port: 5672
                  linkCapacity: 1000
                }
                connector {
                  name: shard_1
                  role: route-container
                  host: 172.17.0.4
                  port: 5672
                  linkCapacity: 1000
                }
                address {
                  prefix: instruction
                  waypoint: yes
                }
                autoLink {
                    addr: instruction
                    dir: in
                    connection: shard_0
                }
                autoLink {
                    addr: instruction
                    dir: out
                    connection: shard_0
                }
                autoLink {
                    addr: instruction
                    dir: in
                    connection: shard_1
                }
                autoLink {
                    addr: instruction
                    dir: out
                    connection: shard_1
                }
            - name: QDROUTERD_SSL_AUTHENTICATE_PEER
              value: "false"
          ports:
            - containerPort: 10452
              name: amqp