apiVersion: v1
kind: Service
metadata:
  name: qdrouterd-service
  labels:
    app: qdrouterd
spec:
  ports:
  - port: 5672
    name: amqp
  # *.nginx.default.svc.cluster.local
  # In case we would have use petset, it looks like we would have well known
  # host name
  selector:
    app: qdrouterd
  #if none previce, ClusterIP is used
  #type: LoadBalancer  
  type: NodePort