apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qdrouterd
  labels:
    app: qdrouterd
spec:
  replicas: 1
  template:
    metadata:
      name: qdrouterd
      labels:
        name: qdrouterd
    spec:
      containers:
        - image: scholzj/qpid-dispatch:0.6.0
          name: qdrouterd
          #imagePullPolicy: Always
          env:
            - name:  QDROUTERD_ADMIN_USERNAME
              value: admin
            - name:  QDROUTERD_ADMIN_PASSWORD
              value: "123456"
            - name: QDROUTERD_CONFIG_INSET
              value: |
                    connector {
                      name: shard_0
                      role: route-container
                      host: 172.17.0.5
                      port: 5672
                      linkCapacity: 1000
                    }
                    connector {
                      name: shard_1
                      role: route-container
                      host: 172.17.0.4
                      port: 5672
                      linkCapacity: 1000
                    }
          ports:
            - containerPort: 5672
              name: amqp