kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qpid-java-storage
  annotations: 
    volume.alpha.kubernetes.io/storage-class: "true"
spec: 
  accessModes: ["ReadWriteOnce"]
  resources:
    requests: 
      storage: 100Mi